<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Phone Operator displayed is: AIRTEL]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="62711" started-at="2016-04-15T10:10:11Z" finished-at="2016-04-15T10:11:13Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="62711" started-at="2016-04-15T10:10:11Z" finished-at="2016-04-15T10:11:13Z">
      <class name="com.pack.test.RechargeTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.pack.test.RechargeTest@68be2bc2]" name="initialize" is-config="true" duration-ms="26828" started-at="2016-04-15T15:40:11Z" finished-at="2016-04-15T15:40:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="rechargePayTM(java.lang.String)[pri:0, instance:com.pack.test.RechargeTest@68be2bc2]" name="rechargePayTM" duration-ms="34523" started-at="2016-04-15T15:40:38Z" finished-at="2016-04-15T15:41:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9740172752]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Airtel] but found [AirteL]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Airtel] but found [AirteL]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.pack.page.Recharge.VerifyOperatorName(Recharge.java:63)
	at com.pack.test.RechargeTest.rechargePayTM(RechargeTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Phone Operator displayed is: AIRTEL]]>
            </line>
          </reporter-output>
        </test-method> <!-- rechargePayTM -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.pack.test.RechargeTest@68be2bc2]" name="tearDown" is-config="true" duration-ms="1296" started-at="2016-04-15T15:41:12Z" finished-at="2016-04-15T15:41:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.pack.test.RechargeTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
